# Generated by Django 3.1.7 on 2021-02-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('chamber', models.CharField(max_length=32, null=True)),
                ('title', models.CharField(max_length=32, null=True)),
                ('short_title', models.CharField(max_length=4, null=True)),
                ('first_name', models.CharField(max_length=32, null=True)),
                ('middle_name', models.CharField(max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('sufffix', models.CharField(max_length=32, null=True)),
                ('date_of_birth', models.CharField(max_length=32, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('party', models.CharField(max_length=32, null=True)),
                ('twitter_account', models.CharField(max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('in_office', models.BooleanField(null=True)),
                ('next_election', models.CharField(max_length=4, null=True)),
                ('total_votes', models.IntegerField(null=True)),
                ('missed_votes', models.IntegerField(null=True)),
                ('total_present', models.IntegerField(null=True)),
                ('office', models.CharField(max_length=512, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('state', models.CharField(max_length=32, null=True)),
                ('missed_votes_pct', models.FloatField(null=True)),
                ('votes_with_party_pct', models.FloatField(null=True)),
                ('votes_against_party_pct', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biographies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('creative_work', models.JSONField(null=True)),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bossApi.members')),
            ],
        ),
    ]
