# Generated by Django 3.1.7 on 2021-02-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bossApi', '0002_remove_biographies_creative_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographies',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='bossApi.members'),
        ),
    ]
